import type { PhraseLibrary } from './types';

/** English version of the French requests, phrase for phrase. */
export const PHRASES_EN: PhraseLibrary = {
  categories: [
    { id: 'summary', label: 'Summary' },
    { id: 'email', label: 'Email' },
    { id: 'writing', label: 'Writing' },
    { id: 'editing', label: 'Editing' },
    { id: 'translation', label: 'Translation' },
    { id: 'meeting', label: 'Meeting' },
    { id: 'understand', label: 'Understand' },
    { id: 'data', label: 'Data' },
    { id: 'legal', label: 'Legal' },
    { id: 'hr', label: 'HR' },
    { id: 'communication', label: 'Communication' },
    { id: 'project', label: 'Project' },
  ],
  phrases: [
    ['summary', 'Summarise this in 5 key points'],
    [
      'summary',
      'Write a one-page summary for my management',
      'summary-report-decider',
    ],
    ['summary', 'Summarise this email and draw an action plan from it'],
    ['summary', 'Write an analytical summary of this text'],
    ['summary', 'Summarise this exchange: decisions and open questions'],
    ['summary', 'Summarise this audit: findings, risks, recommendations'],
    ['summary', 'Summarise this decision in 200 words'],
    ['summary', 'Summarise these reports in a one-page note'],
    [
      'summary',
      'Turn these conclusions into talking points',
      'summary-talking-points',
    ],
    ['summary', 'Sort these contributions by theme', 'summary-consultation'],
    ['summary', 'What are the main takeaways?'],
    ['summary', 'Summarise this email in 3 sentences'],
    ['summary', 'Sort these messages by urgency'],
    ['summary', 'Bring me up to date on this file'],
    ['summary', 'Summarise this presentation in one slide'],
    [
      'summary',
      'Summarise this in a short, medium and long version',
      'summary-versions',
    ],
    ['summary', 'Summarise, starting with what is at stake'],
    ['summary', 'Extract the key figures', 'summary-key-figures'],
    ['summary', 'List the deadlines and dates'],
    [
      'summary',
      'Summarise this email thread before forwarding it',
      'summary-email-thread',
    ],
    ['email', 'Write an email to postpone the meeting'],
    ['email', 'Write a formal email of 10 lines at most'],
    ['email', 'Reply to this email point by point'],
    ['email', 'Tell me where my opinion is expected in this email'],
    ['email', 'Reply to this request'],
    ['email', 'Write a 2-sentence forwarding message', 'mail-forward-context'],
    ['email', 'Write a standard reply to a citizen', 'mail-reply-citizen'],
    [
      'email',
      'Acknowledge receipt and give the processing time',
      'mail-acknowledge',
    ],
    [
      'email',
      'Send a reminder about this missing document',
      'mail-missing-document',
    ],
    ['email', 'Write the meeting follow-up email', 'meeting-debrief'],
    ['email', 'Ask for details about these anomalies'],
    ['email', 'Ask for the updated budget forecasts'],
    ['email', 'Announce these changes to the team', 'mail-announce-change'],
    ['email', 'Thank the workshop participants'],
    ['email', 'Reply to this complaint', 'public-complaint'],
    ['email', 'Explain to staff how to solve this problem'],
    ['email', 'Write my out-of-office message'],
    ['writing', 'Write a briefing note for management', 'summary-note'],
    [
      'writing',
      'Draft an answer to this parliamentary question',
      'writing-parliamentary',
    ],
    ['writing', 'Update this internal note'],
    ['writing', 'Suggest an outline for this note'],
    ['writing', 'Write a project brief', 'project-brief'],
    ['writing', 'Write a bullet-point fact sheet'],
    ['writing', 'Write a report from these findings'],
    ['writing', 'Write an FAQ from this regulation', 'writing-faq'],
    ['writing', 'Write an FAQ in plain language', 'writing-faq'],
    ['writing', 'Create a glossary of the technical terms', 'writing-glossary'],
    ['writing', 'Write a step-by-step tutorial', 'writing-tutorial'],
    ['writing', 'Write a questionnaire for staff', 'writing-questionnaire'],
    [
      'writing',
      'Write a press release from this report',
      'communication-press-release',
    ],
    ['writing', 'Write a procedure sheet', 'writing-procedure'],
    ['writing', 'Assess the risks of this project', 'project-risks'],
    ['writing', 'Write the case for this option'],
    ['writing', 'Write the specifications', 'procurement-specs'],
    ['writing', 'Prepare a 10-slide presentation', 'com-presentation'],
    ['editing', 'Correct the spelling and grammar', 'writing-proofread'],
    ['editing', 'Make this paragraph clearer and more concise'],
    ['editing', 'Suggest improvements'],
    ['editing', 'Cut it by half'],
    ['editing', 'Use a more formal tone'],
    ['editing', 'Remove the technical jargon'],
    ['editing', 'Expand on this point'],
    ['editing', 'Reorganise, starting with what is at stake'],
    [
      'editing',
      'Make this text accessible to the general public',
      'public-accessible',
    ],
    ['editing', 'Adapt this circular for managers'],
    ['editing', 'Rewrite in plain language', 'writing-plain-language'],
    ['editing', 'Write a general-public version and a partner version'],
    ['editing', 'Suggest a catchy title'],
    ['editing', 'Turn this note into a 2-minute speech', 'writing-speech'],
    ['editing', 'Turn these notes into written text'],
    ['editing', 'Point out the ambiguous wording'],
    ['editing', 'Check that it follows clear administrative writing'],
    ['editing', 'Pseudonymise this document'],
    ['editing', 'Compare these two versions', 'summary-compare'],
    ['editing', 'Format it with headings, lists and a table'],
    ['translation', 'Translate into French', 'public-translate'],
    ['translation', 'Translate into German with a glossary'],
    ['translation', 'Translate without changing the technical names'],
    ['translation', 'Quickly translate this document', 'public-translate'],
    [
      'translation',
      'Write an announcement and translate it into two languages',
    ],
    ['translation', 'Translate this email and suggest a reply'],
    ['translation', 'Translate and explain the legal terms'],
    ['translation', 'Check this translation'],
    [
      'meeting',
      'Write the minutes from the transcript',
      'meetings-minutes-transcript',
    ],
    ['meeting', 'Write the minutes from my notes', 'meeting-minutes'],
    ['meeting', 'Turn these notes into an agenda'],
    ['meeting', 'List the actions, owners and deadlines', 'meeting-actions'],
    ['meeting', 'List the questions left unanswered'],
    ['meeting', 'Sum up: takeaways and actions'],
    ['meeting', 'What conclusions should we keep from this meeting?'],
    ['meeting', 'Help me prepare my next meeting'],
    [
      'meeting',
      'Extract the decisions and announcements',
      'meetings-decisions-log',
    ],
    ['meeting', 'Write the minutes of this interview'],
    ['meeting', 'Prepare the questions to ask', 'meetings-questions'],
    ['meeting', 'Write the invitation with the agenda', 'meeting-invitation'],
    ['meeting', 'Prepare my one-to-one meeting'],
    ['meeting', 'Prepare my talking points', 'summary-talking-points'],
    [
      'meeting',
      'Sum up in 3 decisions and 3 actions',
      'meetings-decisions-log',
    ],
    ['understand', 'Explain this notion simply', 'summary-plain'],
    ['understand', 'Explain the basics of this subject'],
    ['understand', 'Explain this procedure to front-desk staff'],
    ['understand', 'Explain these statistics in plain language'],
    ['understand', 'What questions should I ask myself before deciding?'],
    ['understand', 'What is the difference between these two notions?'],
    [
      'understand',
      'What are the steps of this procedure?',
      'public-procedure-explain',
    ],
    ['understand', 'Give me leads for research'],
    ['understand', 'Suggest searches to find the official texts'],
    ['understand', 'What are the points to watch?'],
    ['understand', 'Explain this acronym in its context'],
    ['understand', 'Where is this subject covered? Quote the passage'],
    ['understand', 'Research this subject in depth'],
    ['understand', 'Check whether this statement is accurate'],
    ['data', 'Fix this spreadsheet formula', 'data-formula'],
    ['data', 'Analyse this file: trends and anomalies', 'data-analyse-table'],
    ['data', 'Are there trends in this data?', 'data-analyse-table'],
    ['data', 'Find the inconsistencies in this data', 'data-clean'],
    ['data', 'Create a comparison table'],
    ['data', 'Produce summary tables'],
    ['data', 'Find the budget gaps above 15%', 'data-budget-gaps'],
    ['data', 'Calculate the percentages and totals'],
    ['data', 'Compare the budgets of the last three years'],
    ['data', 'Simulate a 10% drop in revenue'],
    [
      'data',
      'Compare these bids: cost, time, risks',
      'procurement-compare-bids',
    ],
    ['data', 'Remove the duplicates from this table', 'data-clean'],
    ['data', 'Help me build a pivot table', 'data-pivot'],
    ['data', 'Suggest a chart for management', 'data-chart'],
    ['data', 'Identify the most frequent problems'],
    ['data', 'What analyses can I do in the spreadsheet?'],
    ['legal', 'Summarise this law', 'legal-explain-text'],
    [
      'legal',
      'Explain this decree for non-lawyers',
      'procurement-decree-explained',
    ],
    ['legal', 'Find the contradictions with existing texts'],
    ['legal', 'Compare this agreement with the regulations'],
    ['legal', 'Check this procedure is compliant'],
    ['legal', 'What needs revising after this new law?'],
    ['legal', 'What obligations under the EU AI Act?'],
    ['legal', 'Explain the obligations of this circular', 'legal-explain-text'],
    ['legal', 'List the legal references to check'],
    [
      'legal',
      'Point out the risky clauses of this contract',
      'procurement-risky-clauses',
    ],
    ['hr', 'Write feedback for the annual review', 'hr-annual-review'],
    ['hr', 'Write a job description', 'hr-job-offer'],
    ['hr', 'Write a recommendation letter'],
    ['hr', 'Prepare the welcome of a newcomer', 'hr-onboarding'],
    ['hr', 'Suggest job interview questions', 'hr-interview-guide'],
    ['hr', 'Turn my notes into a self-assessment'],
    ['hr', 'Ask my manager for feedback'],
    ['hr', 'Turn my priorities into SMART objectives', 'hr-smart-objectives'],
    ['hr', 'Build a 30, 60, 90-day development plan'],
    ['hr', 'Compare my background with this job description'],
    ['hr', 'Prepare my handover before my absence', 'hr-handover'],
    ['hr', 'Make this message to the team kinder'],
    [
      'communication',
      'Write a message for the chat and the intranet',
      'communication-multichannel',
    ],
    ['communication', 'Write a social media post', 'com-social-post'],
    ['communication', 'Write an emergency release, a text message and a post'],
    ['communication', 'Suggest an infographic for this figure'],
    ['communication', 'Write an intranet article', 'com-news'],
    ['communication', 'Improve this slide'],
    ['communication', 'Suggest 3 hooks for this campaign'],
    ['project', 'Build the timeline of this project'],
    ['project', 'Create the risk register', 'project-risks'],
    ['project', 'Write the progress update', 'project-status'],
    ['project', 'Turn these notes into a task list'],
    ['project', 'Describe the roles and flows in one slide'],
    ['project', 'Suggest shared indicators', 'project-indicators'],
    [
      'project',
      'Write the lessons learned from this crisis',
      'project-lessons',
    ],
    ['project', 'Build a mind map of this subject'],
  ],
};
