import type { PhraseLibrary } from './types';

/** English counterpart of the French phrases, a shorter selection. */
export const PHRASES_EN: PhraseLibrary = {
  categories: [
    { id: 'generic', label: 'Generic' },
    { id: 'summary', label: 'Summary' },
    { id: 'writing', label: 'Writing' },
    { id: 'email', label: 'Email' },
    { id: 'citizen', label: 'Public' },
    { id: 'meeting', label: 'Meeting' },
    { id: 'analysis', label: 'Analysis' },
    { id: 'data', label: 'Data' },
    { id: 'legal', label: 'Legal' },
    { id: 'hr', label: 'HR' },
    { id: 'project', label: 'Project' },
    { id: 'communication', label: 'Communication' },
    { id: 'clarity', label: 'Clarity' },
    { id: 'translation', label: 'Translation' },
  ],
  phrases: [
    ['generic', 'Summarise this in 3 key points'],
    ['generic', 'Challenge this assumption'],
    ['generic', 'Explain this as to a newcomer'],
    ['generic', 'Give me the pros and cons'],
    ['generic', 'Suggest three options and recommend one'],
    ['generic', 'What risks am I not seeing?'],
    ['generic', 'Ask me questions before answering'],
    ['generic', 'Break this problem down into steps'],
    ['summary', 'Write a one-page summary for a decision maker'],
    ['summary', 'Extract the decisions and actions'],
    ['summary', 'Give me the gist in one sentence'],
    ['summary', 'Summarise this email thread'],
    ['summary', 'List the key figures in this document'],
    ['writing', 'Write a briefing note for my management'],
    ['writing', 'Improve the style without changing the substance'],
    ['writing', 'Cut this text by half'],
    ['writing', 'Turn these notes into a written text'],
    ['writing', 'Write a step-by-step procedure'],
    ['email', 'Reply to this email politely'],
    ['email', 'Write a polite but firm reminder'],
    ['email', 'Decline this request tactfully'],
    ['email', 'Write a thank-you email'],
    ['citizen', 'Answer this citizen simply, without jargon'],
    ['citizen', 'Reply to this complaint with empathy'],
    ['citizen', 'Explain this procedure step by step'],
    ['meeting', 'Write the minutes of this meeting'],
    ['meeting', 'Prepare a timed agenda'],
    ['meeting', 'Extract who does what and by when'],
    ['meeting', 'Summarise the meeting for those absent'],
    ['analysis', 'Do a SWOT analysis'],
    ['analysis', 'Find the root causes of this problem'],
    ['analysis', 'Analyse the impacts of this decision'],
    ['analysis', 'Build a risk matrix'],
    ['data', 'Analyse this table and give the trends'],
    ['data', 'Write the spreadsheet formula for this calculation'],
    ['data', 'Suggest a chart suited to this data'],
    ['legal', 'Explain this regulation simply'],
    ['legal', 'What obligations follow from it?'],
    ['hr', 'Write a job description'],
    ['hr', 'Prepare an annual review'],
    ['hr', 'Write SMART objectives'],
    ['project', 'Write an action plan with deadlines'],
    ['project', 'Write the project brief'],
    ['project', 'Write a progress update'],
    ['communication', 'Write a press release'],
    ['communication', 'Write the text for five slides'],
    ['clarity', 'Rewrite this in plain language'],
    ['clarity', 'Remove the administrative jargon'],
    ['translation', 'Translate this into French'],
    ['translation', 'Translate this keeping a formal tone'],
  ],
};
