import type { PhraseLibrary } from './types';

/**
 * The requests public servants make most often, in short form: one click
 * puts the sentence in the message field.
 */
export const PHRASES_FR: PhraseLibrary = {
  categories: [
    { id: 'summary', label: 'Synthèse' },
    { id: 'email', label: 'Courriel' },
    { id: 'writing', label: 'Rédaction' },
    { id: 'editing', label: 'Relecture' },
    { id: 'translation', label: 'Traduction' },
    { id: 'meeting', label: 'Réunion' },
    { id: 'understand', label: 'Comprendre' },
    { id: 'data', label: 'Données' },
    { id: 'legal', label: 'Juridique' },
    { id: 'hr', label: 'RH' },
    { id: 'communication', label: 'Communication' },
    { id: 'project', label: 'Projet' },
  ],
  phrases: [
    ['summary', 'Résume ceci en 5 points clés'],
    [
      'summary',
      'Fais une synthèse d’une page pour ma direction',
      'summary-report-decider',
    ],
    ['summary', 'Synthétise ce mail et déduis-en un plan d’action'],
    ['summary', 'Fais une synthèse analytique de ce texte'],
    ['summary', 'Résume cet échange : décisions et questions ouvertes'],
    ['summary', 'Résume cet audit : constats, risques, recommandations'],
    ['summary', 'Résume cette délibération en 200 mots'],
    ['summary', 'Résume ces bilans en une note d’une page'],
    [
      'summary',
      'Transforme ces conclusions en éléments de langage',
      'summary-talking-points',
    ],
    ['summary', 'Classe ces contributions par thème', 'summary-consultation'],
    ['summary', 'Quels sont les principaux enseignements ?'],
    ['summary', 'Résume ce mail en 3 phrases'],
    ['summary', 'Classe ces messages par urgence'],
    ['summary', 'Fais-moi le point sur ce dossier'],
    ['summary', 'Résume cette présentation en une diapositive'],
    [
      'summary',
      'Résume ceci en version courte, moyenne et longue',
      'summary-versions',
    ],
    ['summary', 'Résume en commençant par les enjeux'],
    ['summary', 'Extrais les chiffres clés', 'summary-key-figures'],
    ['summary', 'Liste les échéances et les dates'],
    [
      'summary',
      'Résume ce fil de mails avant de le transférer',
      'summary-email-thread',
    ],
    ['email', 'Rédige un courriel pour reporter la réunion'],
    ['email', 'Rédige un courriel formel de 10 lignes maximum'],
    ['email', 'Réponds à ce courriel point par point'],
    ['email', 'Dis-moi où mon avis est attendu dans ce courriel'],
    ['email', 'Réponds à cette sollicitation'],
    [
      'email',
      'Rédige un message de transfert en 2 phrases',
      'mail-forward-context',
    ],
    ['email', 'Rédige une réponse type à un usager', 'mail-reply-citizen'],
    [
      'email',
      'Accuse réception et indique le délai de traitement',
      'mail-acknowledge',
    ],
    ['email', 'Relance pour cette pièce manquante', 'mail-missing-document'],
    ['email', 'Rédige le courriel de suivi de la réunion', 'meeting-debrief'],
    ['email', 'Demande des précisions sur ces anomalies'],
    ['email', 'Demande les prévisions budgétaires actualisées'],
    ['email', 'Annonce ces changements à l’équipe', 'mail-announce-change'],
    ['email', 'Remercie les participants de l’atelier'],
    ['email', 'Réponds à cette réclamation', 'public-complaint'],
    ['email', 'Explique aux agents comment résoudre ce problème'],
    ['email', 'Rédige mon message d’absence'],
    [
      'writing',
      'Rédige une note de synthèse pour la direction',
      'summary-note',
    ],
    [
      'writing',
      'Rédige une réponse à cette question parlementaire',
      'writing-parliamentary',
    ],
    ['writing', 'Mets à jour cette note interne'],
    ['writing', 'Propose un plan pour cette note'],
    ['writing', 'Rédige une note de cadrage', 'project-brief'],
    ['writing', 'Rédige une fiche de synthèse à puces'],
    ['writing', 'Rédige un rapport à partir de ces constats'],
    ['writing', 'Rédige une FAQ à partir de ce règlement', 'writing-faq'],
    ['writing', 'Rédige une FAQ en langage clair', 'writing-faq'],
    ['writing', 'Crée un glossaire des termes techniques', 'writing-glossary'],
    ['writing', 'Rédige un tutoriel pas à pas', 'writing-tutorial'],
    [
      'writing',
      'Rédige un questionnaire pour les agents',
      'writing-questionnaire',
    ],
    [
      'writing',
      'Rédige un communiqué à partir de ce rapport',
      'communication-press-release',
    ],
    ['writing', 'Rédige une fiche de procédure', 'writing-procedure'],
    ['writing', 'Évalue les risques de ce projet', 'project-risks'],
    ['writing', 'Rédige un argumentaire pour cette option'],
    ['writing', 'Rédige le cahier des charges', 'procurement-specs'],
    [
      'writing',
      'Prépare une présentation de 10 diapositives',
      'com-presentation',
    ],
    ['editing', 'Corrige l’orthographe et la grammaire', 'writing-proofread'],
    ['editing', 'Rends ce paragraphe plus clair et concis'],
    ['editing', 'Propose des améliorations'],
    ['editing', 'Raccourcis de moitié'],
    ['editing', 'Utilise un ton plus formel'],
    ['editing', 'Supprime le jargon technique'],
    ['editing', 'Développe davantage ce point'],
    ['editing', 'Réorganise en commençant par les enjeux'],
    [
      'editing',
      'Rends ce texte accessible au grand public',
      'public-accessible',
    ],
    ['editing', 'Adapte cette circulaire pour les managers'],
    ['editing', 'Réécris en langage clair', 'writing-plain-language'],
    ['editing', 'Fais une version grand public et une version partenaires'],
    ['editing', 'Propose un titre accrocheur'],
    [
      'editing',
      'Transforme cette note en discours de 2 minutes',
      'writing-speech',
    ],
    ['editing', 'Transforme ces notes en texte rédigé'],
    ['editing', 'Signale les formulations ambiguës'],
    ['editing', 'Vérifie le respect de l’écriture administrative claire'],
    ['editing', 'Pseudonymise ce document'],
    ['editing', 'Compare ces deux versions', 'summary-compare'],
    ['editing', 'Mets en forme avec titres, listes et tableau'],
    ['translation', 'Traduis en anglais', 'public-translate'],
    ['translation', 'Traduis en allemand avec un glossaire'],
    ['translation', 'Traduis sans modifier les noms techniques'],
    ['translation', 'Traduis rapidement ce document', 'public-translate'],
    ['translation', 'Rédige une annonce et traduis-la en deux langues'],
    ['translation', 'Traduis ce courriel et propose une réponse'],
    ['translation', 'Traduis et explique les termes juridiques'],
    ['translation', 'Vérifie cette traduction'],
    [
      'meeting',
      'Fais le compte rendu à partir de la transcription',
      'meetings-minutes-transcript',
    ],
    [
      'meeting',
      'Fais le compte rendu à partir de mes notes',
      'meeting-minutes',
    ],
    ['meeting', 'Transforme ces notes en ordre du jour'],
    [
      'meeting',
      'Liste les actions, les responsables et les échéances',
      'meeting-actions',
    ],
    ['meeting', 'Liste les questions restées sans réponse'],
    ['meeting', 'Fais le point : enseignements et actions'],
    ['meeting', 'Quelles conclusions retenir de cette réunion ?'],
    ['meeting', 'Aide-moi à préparer ma prochaine réunion'],
    [
      'meeting',
      'Extrais les décisions et les annonces',
      'meetings-decisions-log',
    ],
    ['meeting', 'Fais le compte rendu de cet entretien'],
    ['meeting', 'Prépare les questions à poser', 'meetings-questions'],
    [
      'meeting',
      'Rédige l’invitation avec l’ordre du jour',
      'meeting-invitation',
    ],
    ['meeting', 'Prépare mon entretien individuel'],
    ['meeting', 'Prépare mes éléments de langage', 'summary-talking-points'],
    ['meeting', 'Résume en 3 décisions et 3 actions', 'meetings-decisions-log'],
    ['understand', 'Explique-moi simplement cette notion', 'summary-plain'],
    ['understand', 'Explique-moi les bases de ce sujet'],
    ['understand', 'Explique cette procédure aux agents d’accueil'],
    ['understand', 'Explique ces statistiques en langage clair'],
    ['understand', 'Quelles questions me poser avant de décider ?'],
    ['understand', 'Quelle est la différence entre ces deux notions ?'],
    [
      'understand',
      'Quelles sont les étapes de cette démarche ?',
      'public-procedure-explain',
    ],
    ['understand', 'Donne-moi des pistes de recherche'],
    ['understand', 'Propose des requêtes pour trouver les textes officiels'],
    ['understand', 'Quels sont les points de vigilance ?'],
    ['understand', 'Explique ce sigle dans son contexte'],
    ['understand', 'Où ce sujet est-il traité ? Cite le passage'],
    ['understand', 'Fais une recherche approfondie sur ce sujet'],
    ['understand', 'Vérifie si cette affirmation est exacte'],
    ['data', 'Corrige cette formule de tableur', 'data-formula'],
    [
      'data',
      'Analyse ce fichier : tendances et anomalies',
      'data-analyse-table',
    ],
    ['data', 'Y a-t-il des tendances dans ces données ?', 'data-analyse-table'],
    ['data', 'Repère les incohérences dans ces données', 'data-clean'],
    ['data', 'Crée un tableau comparatif'],
    ['data', 'Produis des tableaux de synthèse'],
    [
      'data',
      'Repère les écarts budgétaires de plus de 15 %',
      'data-budget-gaps',
    ],
    ['data', 'Calcule les pourcentages et les totaux'],
    ['data', 'Compare les budgets des trois dernières années'],
    ['data', 'Simule une baisse de 10 % des recettes'],
    [
      'data',
      'Compare ces offres : coût, délais, risques',
      'procurement-compare-bids',
    ],
    ['data', 'Supprime les doublons de ce tableau', 'data-clean'],
    ['data', 'Aide-moi à faire un tableau croisé dynamique', 'data-pivot'],
    ['data', 'Propose un graphique pour la direction', 'data-chart'],
    ['data', 'Identifie les problèmes les plus fréquents'],
    ['data', 'Quelles analyses faire dans le tableur ?'],
    ['legal', 'Résume ce texte de loi', 'legal-explain-text'],
    [
      'legal',
      'Vulgarise ce décret pour des non-juristes',
      'procurement-decree-explained',
    ],
    ['legal', 'Repère les contradictions avec les textes existants'],
    ['legal', 'Compare cette convention à la réglementation'],
    ['legal', 'Vérifie la conformité de cette procédure'],
    ['legal', 'Que faut-il réviser après cette nouvelle loi ?'],
    ['legal', 'Quelles obligations du règlement européen sur l’IA ?'],
    [
      'legal',
      'Explique les obligations de cette circulaire',
      'legal-explain-text',
    ],
    ['legal', 'Liste les références juridiques à vérifier'],
    [
      'legal',
      'Signale les clauses à risque de ce contrat',
      'procurement-risky-clauses',
    ],
    ['hr', 'Rédige un retour pour l’entretien annuel', 'hr-annual-review'],
    ['hr', 'Rédige une fiche de poste', 'hr-job-offer'],
    ['hr', 'Rédige une lettre de recommandation'],
    ['hr', 'Prépare l’accueil d’un nouvel arrivant', 'hr-onboarding'],
    [
      'hr',
      'Propose des questions d’entretien de recrutement',
      'hr-interview-guide',
    ],
    ['hr', 'Transforme mes notes en auto-évaluation'],
    ['hr', 'Demande un retour à mon responsable'],
    [
      'hr',
      'Transforme mes priorités en objectifs SMART',
      'hr-smart-objectives',
    ],
    ['hr', 'Construis un plan de développement à 30, 60, 90 jours'],
    ['hr', 'Compare mon parcours à cette fiche de poste'],
    ['hr', 'Prépare ma passation avant mon absence', 'hr-handover'],
    ['hr', 'Rends ce message à l’équipe plus bienveillant'],
    [
      'communication',
      'Rédige un message pour Tchap et pour l’intranet',
      'communication-multichannel',
    ],
    [
      'communication',
      'Rédige une publication pour les réseaux sociaux',
      'com-social-post',
    ],
    ['communication', 'Rédige un communiqué d’urgence, un SMS et un post'],
    ['communication', 'Propose une infographie pour ce chiffre'],
    ['communication', 'Rédige un article d’intranet', 'com-news'],
    ['communication', 'Améliore cette diapositive'],
    ['communication', 'Propose 3 accroches pour cette campagne'],
    ['project', 'Construis la chronologie de ce projet'],
    ['project', 'Crée le registre des risques', 'project-risks'],
    ['project', 'Rédige le point d’avancement', 'project-status'],
    ['project', 'Transforme ces notes en liste de tâches'],
    ['project', 'Décris les rôles et les flux en une diapositive'],
    ['project', 'Propose des indicateurs partagés', 'project-indicators'],
    [
      'project',
      'Fais le retour d’expérience de cette crise',
      'project-lessons',
    ],
    ['project', 'Construis une carte mentale de ce sujet'],
  ],
};
